name: Push to subrepositories
on:
  push:
    branches:
      - 'main'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Push recent commits to subrepositories'
      env:
        ACCESS_TOKEN: ${{ secrets.HEXOPS_MACH_PUSH_SUBREPOS }}
      run: |
        git config user.name 'Repository synchronization automation'
        git config user.email 'stephen@hexops.com'
        ./dev/push-subrepos.sh
